### ISSUE TITLE
Latest nightly does not ask for brightness system permission, crashes instead

### ISSUE THREAD

**Issue by rancidfrog** [GeoffreyMetais/vlc-android#1]
VLC-Android-2.1.0-20170223-1056-ARMv7
Overall looks good.

However, Permission popup does not appear anymore on latest night lies.
Vlc crashes when trying to change brightness by swiping left side if screen up/down
```
java.lang.SecurityException: org.videolan.vlc.debug was not granted  this permission: android.permission.WRITE_SETTINGS.
	at android.os.Parcel.readException(Parcel.java:1684)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.call(ContentProviderNative.java:646)
	at android.provider.Settings$NameValueCache.putStringForUser(Settings.java:1578)
	at android.provider.Settings$System.putStringForUser(Settings.java:1949)
	at android.provider.Settings$System.putIntForUser(Settings.java:2054)
	at android.provider.Settings$System.putInt(Settings.java:2048)
	at org.videolan.vlc.gui.video.VideoPlayerActivity.initBrightnessTouch(VideoPlayerActivity.java:2200)
	at org.videolan.vlc.gui.video.VideoPlayerActivity.doBrightnessTouch(VideoPlayerActivity.java:2220)
	at org.videolan.vlc.gui.video.VideoPlayerActivity.onTouchEvent(VideoPlayerActivity.java:2089)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3064)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:375)
	at android.view.View.dispatchPointerEvent(View.java:10243)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4444)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4312)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4005)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4062)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6252)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6226)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6187)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6355)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6326)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6378)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
	at android.view.Choreographer.doFrame(Choreographer.java:615)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6169)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
	at Android.MODEL(Xperia z3c)
	at Android.VERSION(7.1.1)

```
Permission needs to be set by manually going to app info and enabling permissions.

Also
Video tab refreshes each time, takes time with animation before appearing.
And when autorescan is off videos do not appear.
Sometimes after downloading video, video appears mor than once in video tab 

Forum and track has issues when logging in:
- Environment not found
-  No route found for "GET /ucp.php"

Seems like using VPN works sometimes, but annoying that needs VPN to use forum/trac

**Comment by GeoffreyMetais** [comment]
This is fixed on (videolan) master.

**Comment by rancidfrog** [comment]
@GeoffreyMetais 
Weird, in the last few nightly builds brightness popup request does not appear, yet app does not crash anymore. (After uninstalling and installing new nightlies, starting from last few 2.1.1 builds and 2.1.2).
Do not know why, though.
Brightness changes without granting request
